"""
Run calibrations for the HIV Eswatini model
"""

# Additions to handle numpy multithreading
import os
os.environ.update(
    OMP_NUM_THREADS='1', 
    OPENBLAS_NUM_THREADS='1',
    NUMEXPR_NUM_THREADS='1',
    MKL_NUM_THREADS='1',
)

# %% Imports and settings
from pathlib import Path
import numpy as np
import sciris as sc
import stisim as sti
import pandas as pd
from run_sims import make_sim


# Constants — paths anchored to the repo root.
LOCATION = 'eswatini'
REPO_DIR = Path(__file__).parent
DATA_DIR = REPO_DIR / 'data'
RESULTS_DIR = REPO_DIR / 'results'
FIGURES_DIR = REPO_DIR / 'figures'


# Run settings
TOTAL_TRIALS = 1000
storage = None
do_shrink = True  # Whether to shrink the calibration results


def make_calibration():
    """ Build the Optuna-backed calibration object for the Eswatini HIV model.

    Defines the calibration parameter ranges (HIV transmission, condom efficacy,
    ART duration, and network composition), the data source, and the Calibration
    runner. Does not start trials — call ``calib.calibrate()`` on the return value.

    Returns:
        tuple: ``(sim, calib)`` — the base sim and an unstarted ``sti.Calibration``.
    """
    # Define the calibration parameters
    ckw = dict(suggest_type='suggest_float')
    calib_pars = dict(
        hiv=dict(
            beta_m2f=      dict(low=0.002, high=0.014, guess=0.006, **ckw),
            eff_condom=    dict(low=0.5, high=0.9, guess=0.75, **ckw),
            # rel_init_prev= dict(low=2, high=15, guess=8, **ckw),
            rel_dur_on_art=dict(low=1.0, high=20.0, guess=8.0, **ckw),
        ),
        structuredsexual=dict(
            prop_f0= dict(low=0.55, high=0.9, guess=0.7, **ckw),
            prop_m0= dict(low=0.55, high=0.8, guess=0.65, **ckw),
            m1_conc= dict(low=0.05, high=0.3, guess=0.15, **ckw),
        ),
    )

    # Minimal extra results — just core epi for calibration display.
    # Comprehensive results are generated by run_msim.py with the best pars.
    sres = ['hiv.n_on_art', 'n_alive']

    sim = make_sim(verbose=-1, seed=1)
    data = pd.read_csv(DATA_DIR / f'{LOCATION}_hiv_calib.csv')

    weights = {
    }

    calib = sti.Calibration(
        calib_pars=calib_pars,
        extra_results=sres,
        weights=weights,
        sim=sim,
        data=data,
        study_name=f'{LOCATION}_calibration',
        total_trials=TOTAL_TRIALS,
        die=False, reseed=False, storage=storage, save_results=True,
        continue_db=True, keep_db=True,
    )

    return sim, calib


if __name__ == '__main__':

    do_run = True

    if do_run:
        sim, calib = make_calibration()
        sc.heading(f'Running calibration, {TOTAL_TRIALS} trials')
        calib.calibrate()
        print(f'Best pars are {calib.best_pars}')
        calib.remove_db()
        calib.save(str(RESULTS_DIR / f'{LOCATION}_calib.obj'), shrink=do_shrink,
                   pars_filename=str(RESULTS_DIR / f'{LOCATION}_pars.df'))
    else:
        calib = sc.loadobj(RESULTS_DIR / f'{LOCATION}_calib.obj')

    print('Done!')


